### ISSUE TITLE
Out of bounds read when a required element is missing from an object and this is logged

### ISSUE THREAD

**Issue by badicsalex** [badicsalex/json_schema_to_c#46]
CURRENT_TOKEN() may point to the token after valid tokens, if this is the top level object.

jsmn.h needs to be checked if it allocates an EOF token or not (probably not)

This causes the following valgrind error: Conditional jump or move depends on uninitialised value(s)

**Comment by badicsalex** [comment]
Running with msan (instead of asan) gives the following error:
```
==300992==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5632c5305368 in check_error /home/alex/projects/cms/json_schema_to_c/tests/other/errors.parser.c:30:9
    #1 0x5632c530482c in main /home/alex/projects/cms/json_schema_to_c/tests/other/errors.c:188:5
    #2 0x7f2ea52da151 in __libc_start_main (/usr/lib/libc.so.6+0x28151)
    #3 0x5632c528718d in _start (/home/alex/projects/cms/json_schema_to_c/tests/other/errors.compiled+0x2018d)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /home/alex/projects/cms/json_schema_to_c/tests/other/errors.parser.c:30:9 in check_error
```
